config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'
  
  #Forum yolları------------------------------------------------
  get '/forumlar',    to: 'forums#index', as: :forums
  get '/forumlar/:id', to: 'forums#show',  as: :forum 
  #-------------------------------------------------------------

  #Kullanıcı yolları--------------------------------------------
  resource :session, only:[:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  #/users/new adresini /kaydol a yönlendir
  get '/users/new', to: redirect('/kaydol')
  #index için rota oluştur ma
  resources :users, except: :index
  #bu kod register_path ve register_url oluşturur
  get '/kaydol', to: 'users#new', as: :register
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  #-------------------------------------------------------------
  
  #konular yolları----------------------------------------------
  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', 
                                              path_names: {new: 'yeni'}
  end
  
  resources :topics, except: [:index, :new, :create], 
                     path: 'konular', 
                     path_names: {edit: 'duzenle'} do
     #yorumlar
     resources :comments, only: [:new, :create],
                          path: 'yorumlar',
                          path_names: {new: 'yeni'}
                     
  end
  #-------------------------------------------------------------
  #yorumlar-----------------------------------------------------
  resources :comments, only: [:edit, :update, :destroy],
                       path: 'yorumlar',
                       path_names: {edit: 'duzenle'}
  #-------------------------------------------------------------
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :comments, through: :topics

  validates :name, presence: true, uniqueness: true
  
  def to_param
    name
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.all
    @topics = Topic.includes(:forum, :user)
  end

  def show
    @forums = Forum.all
    @forum = Forum.find_by_name(params[:id])
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_forum.html.erb
<!-- syntax_highlighting: html -->
<li><%= link_to forum.name, forum %></li>

app/views/forums/index.html.erb
<!-- syntax_highlighting: html -->
<% content_for(:forum_content) do %>
  <div class="large-12 columns">
    <h1>Hoş Geldiniz.</h1><hr>
    <div class="topics panel columns">
      <% if @topics.any? %>
        <%= render @topics %>
      <% else %>
        <p>Henüz hiçbir konu açılmamış.</p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/forums/show.html.erb
<!-- syntax_highlighting: html -->
<% content_for(:forum_content) do %>
  <div class="large-12 columns">
    <h1 class="left"><%= @forum.name %> Forumu</h1>
    <% if signed_in? %>
      <%= link_to 'Konu Aç', new_forum_topic_path(@forum), class: 'button right',
                             style: 'margin-top: 10px' %><hr>
    <% end %>
    <div class="topics panel columns">
      <% if @forum.topics.any? %>
        <%= render @forum.topics %>
      <% else %>,
        <p>Henüz hiçbir konu açılmamış.</p>
      <% end %>
    </div>
  </div>
<% end %>