config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'
  
  #Forum yolları------------------------------------------------
  get '/forumlar',    to: 'forums#index', as: :forums
  get '/forumlar/:id', to: 'forums#show',  as: :forum 
  #-------------------------------------------------------------

  #Kullanıcı yolları--------------------------------------------
  resource :session, only:[:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  #/users/new adresini /kaydol a yönlendir
  get '/users/new', to: redirect('/kaydol')
  #index için rota oluştur ma
  resources :users, except: :index
  #bu kod register_path ve register_url oluşturur
  get '/kaydol', to: 'users#new', as: :register
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  #-------------------------------------------------------------
  
  #konular yolları----------------------------------------------
  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', 
                                              path_names: {new: 'yeni'}
  end
  
  resources :topics, except: [:index, :new, :create], 
                     path: 'konular', 
                     path_names: {edit: 'duzenle'} do
     #yorumlar
     resources :comments, only: [:new, :create],
                          path: 'yorumlar',
                          path_names: {new: 'yeni'}
                     
  end
  #-------------------------------------------------------------
  #yorumlar-----------------------------------------------------
  resources :comments, only: [:edit, :update, :destroy],
                       path: 'yorumlar',
                       path_names: {edit: 'duzenle'}
  #-------------------------------------------------------------
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic, counter_cache: true
  
  validates :body,   presence: true
  validates :user,   presence: true
  validates :topic,  presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :validate_user!
  before_action only: [:edit, :update, :destroy] do
    validate_permission!(select_comment.user)
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params)
    @comment.user = current_user
    
    if @comment.save
      redirect_to topic_url(@topic), notice: 'Yorumunuz eklendi.'
    else
      render :new
    end
  end 
  
  def edit
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to topic_url(@comment.topic), notice: 'Yorumunuz başarıyla güncellendi.'
    else
      render :edit
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to topic_url(@comment.topic), notice: 'Yorumunuz başarıyla silindi.'
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
  def select_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- syntax_highlighting: html -->
<div class="comment">
  <p><%= comment.body %></p>
  
  <div class="details">
    <%= link_to comment.user.username, profile_path(comment.user) %> tarafından
    <%= time_ago_in_words comment.created_at %> önce gönderildi.
    
    <% if current_user == comment.user %>
      <%= link_to 'Düzenle', edit_comment_path(comment) %>
      <%= link_to 'Sil', comment, method: :delete, data: {confirm: 'Yorumu silmek istediğine emin misin?'} %>
    <% end %>
  </div>
</div><hr>

app/views/comments/_form.html.erb
<!-- syntax_highlighting: html -->
<%= form_for form_params(@topic, @comment) do |form| %>
  <%= render 'layouts/form_errors', object: @comment %>
  
  <%= form.text_area :body, class: 'comment-area' %>
  <%= form.submit class: 'tiny button' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Yorumu Düzenle</h1>
<%= render 'form' %>

app/views/comments/new.html.erb
<!-- syntax_highlighting: html -->
<div class="topics panel columns">
  <h2><%= @topic.title %></h2>
  <p><%= @topic.body %></p>
  
  <div class="details">
    <span class="forum-name">
      <%= link_to @topic.forum.name, @topic.forum %>
    </span>
    
    <%= link_to @topic.user.username, profile_path(@topic.user) %> tarafından
    <%= time_ago_in_words @topic.created_at %> önce gönderildi.
  </div>
  
  <div class="small-11 columns offset-1">
    <h4>Konuya yorum yapın.</h4>
    <%= render 'form' %>
  </div>
</div>