config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'
  
  #Forum yolları------------------------------------------------
  get '/forumlar',    to: 'forums#index', as: :forums
  get '/forumlar/:id', to: 'forums#show',  as: :forum 
  #-------------------------------------------------------------

  #Kullanıcı yolları--------------------------------------------
  resource :session, only:[:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  #/users/new adresini /kaydol a yönlendir
  get '/users/new', to: redirect('/kaydol')
  #index için rota oluştur ma
  resources :users, except: :index
  #bu kod register_path ve register_url oluşturur
  get '/kaydol', to: 'users#new', as: :register
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  #-------------------------------------------------------------
  
  #konular yolları----------------------------------------------
  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', 
                                              path_names: {new: 'yeni'}
  end
  
  resources :topics, except: [:index, :new, :create], 
                     path: 'konular', 
                     path_names: {edit: 'duzenle'} do
     #yorumlar
     resources :comments, only: [:new, :create],
                          path: 'yorumlar',
                          path_names: {new: 'yeni'}
                     
  end
  #-------------------------------------------------------------
  #yorumlar-----------------------------------------------------
  resources :comments, only: [:edit, :update, :destroy],
                       path: 'yorumlar',
                       path_names: {edit: 'duzenle'}
  #-------------------------------------------------------------
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  belongs_to :forum
  has_many :comments, dependent: :destroy
  default_scope {order 'created_at DESC'}
  
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 20}
  
  #bu şekilde tanımlandığında user_id ve forum_id alanlarına,
  #böyle bir kullanıcı ve konu olmadığı halde atama yapılabiir.
  #-------------------------------------------------------------
  #validates :user_id, presence: true
  #validates :forum_id, presence: true
  
  #yukardaki durumu düzeltmek için, yani varolan bir kullanıcı,
  #ve konuya sadece atama yapmak için ilişkilerin ismi kullanılır;
  validates :user, presence: true
  validates :forum, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :validate_user!, except: [:show]
  before_action only: [:edit, :update, :destroy] do
    validate_permission!(set_topic.user)
  end

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @forum = Forum.find_by_name(params[:forum_id])
    @topic = @forum.topics.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @forum = Forum.find_by_name(params[:forum_id])
    @topic = @forum.topics.new(topic_params)
    @topic.user = current_user
    
    if @topic.save
      redirect_to topic_url(@topic), notice: 'Konu başarıyla oluşturuldu.'
    else
      render :new     
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    if @topic.update(topic_params)
      redirect_to topic_url(@topic), notice: 'Konu başarıyla güncellendi.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    redirect_to root_url, notice: 'Konu başarıyla silindi.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :body)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<!-- syntax_highlighting: html -->
<div class="large-12 medium-12 medium-centered columns">
  <%= form_for form_params(@forum, @topic) do |f| %>
    <%= render 'layouts/form_errors', object: @topic %>
    
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.submit class: 'small button right'%>
    </div>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<!-- syntax_highlighting: html -->
<div style="margin-bottom: 10px" class="topic columns">
  <div class="small-10 columns">
    <h5><%= link_to topic.title, topic %></h5>
    <p><%= markdown truncate(topic.body, length: 50, escape: false), links: false %></p>
    
    <div class="details">
      <% unless params[:action] == 'show' && params[:controller] == 'forums' %>
        <span class="forum-name">
          <%= link_to topic.forum.name, topic.forum, class: 'badge' %>
        </span>
      <% end %>
      <%= link_to_unless_current topic.user.username, profile_path(topic.user) %> tarafından
      <%= time_ago_in_words topic.created_at %> önce gönderildi.
    </div>
  </div>
  
  <div class="small-2 columns text-center answer-count">
    <strong><%= topic.comments.count %></strong><br> Yanıt
  </div>
</div><hr>

app/views/topics/edit.html.erb
<!-- syntax_highlighting: html -->
<h1>Konuyu Düzenle</h1>

<div class="large-12 medium-12 medium-centered columns">
  <%= form_for @topic do |f| %>
    <% if @topic.errors.any? %>
      <div class="row panel callout radius">
        <p>Aşağıdaki hataları düzeltip tekrar deneyiniz.</p>
        <ul class="square">
          <% @topic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div>
      <%= f.submit class: 'small button right'%>
    </div>
  <% end %>
</div>

app/views/topics/index.html.erb
<!-- syntax_highlighting: html -->
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<!-- syntax_highlighting: html -->
<h1>Yeni Konu</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<!-- syntax_highlighting: html -->
<%= provide :title, 'Konular' %>
<div class="topics panel columns">
  <h2><%= @topic.title %></h2>
  <p><%= markdown @topic.body %></p>
  
  <div class="details">
    <span class="forum-name">
      <%= link_to @topic.forum.name, @topic.forum %>
    </span>
    <%= link_to_unless_current @topic.user.username, profile_path(@topic.user) %>
    tarafından <%= time_ago_in_words @topic.created_at %> önce gönderildi.
  </div>
</div>

<div>
  <%= link_to 'Yorum Ekle', new_topic_comment_path(@topic   ), class: 'tiny button' if signed_in? %>
  <% if current_user == @topic.user %>
    <%= link_to 'Düzenle', edit_topic_path(@topic), class: 'tiny button' %>
    <%= link_to 'Sil', @topic, method: :delete, class: 'tiny button alert',
                               data: {confirm: 'Konuyu silmek istediğinize emin misiniz?'} %>
  <% end %>
</div>

<div class="comments">
  <h2>Yorumlar (<%= @topic.comments.count %>)</h2><hr>
  <%= render @topic.comments %>
</div>