config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'
  
  #Forum yolları------------------------------------------------
  get '/forumlar',    to: 'forums#index', as: :forums
  get '/forumlar/:id', to: 'forums#show',  as: :forum 
  #-------------------------------------------------------------

  #Kullanıcı yolları--------------------------------------------
  resource :session, only:[:new, :create, :destroy]
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturumu_kapat', to: 'sessions#destroy', as: :logout

  #/users/new adresini /kaydol a yönlendir
  get '/users/new', to: redirect('/kaydol')
  #index için rota oluştur ma
  resources :users, except: :index
  #bu kod register_path ve register_url oluşturur
  get '/kaydol', to: 'users#new', as: :register
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile
  #-------------------------------------------------------------
  
  #konular yolları----------------------------------------------
  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', 
                                              path_names: {new: 'yeni'}
  end
  
  resources :topics, except: [:index, :new, :create], 
                     path: 'konular', 
                     path_names: {edit: 'duzenle'} do
     #yorumlar
     resources :comments, only: [:new, :create],
                          path: 'yorumlar',
                          path_names: {new: 'yeni'}
                     
  end
  #-------------------------------------------------------------
  #yorumlar-----------------------------------------------------
  resources :comments, only: [:edit, :update, :destroy],
                       path: 'yorumlar',
                       path_names: {edit: 'duzenle'}
  #-------------------------------------------------------------
end

app/views/layouts/_flash_messages.html.erb
<!-- syntax_highlighting: html -->
<% flash.each do |type, message| %>
    <div data-alert class="alert-box <%= flash_class(type) %>">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<!-- syntax_highlighting: html -->
<% if object.errors.any? %>
  <div class="row panel callout radius">
    <p>Aşağıdaki hataları düzeltip, tekrar deneyin.</p>
    <ul class="square">
      <% object.errors.full_messages.each do |m| %>
          <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_profile.html.erb
<!-- syntax_highlighting: html -->
<% content_for(:content) do %>
<div style="padding-top: 15px" class="row">
    <div class="large-2 columns">
      <%= image_tag @user.avatar_url, class: 'profile-image' %>
    </div>

    <div class="large-10 columns">
      <h2><%= "#{@user.first_name} #{@user.last_name}" %></h2>
      <p><%= @user.email %></p>
      <div class="button-bar">
        <ul class="button-group radius">
          <li><%= link_to 'Konular', profile_path(@user, sayfa: 'konular'),
                          class: 'small button secondary' %></li>
          <li><%= link_to 'Yorumlar', profile_path(@user, sayfa: 'yorumlar'),
                          class: 'small button secondary' %></li>
          <% if current_user == @user %>
            <li><%= link_to 'Profilimi Düzenle', edit_profile_path(@user),
                            class: 'small button secondary' %></li>
            <li><%= link_to 'Hesabımı Sil', @user,
                            class: 'small button alert',
                            method: :delete,
                            data: {confirm: 'Hesabınızı silmek istediğinize
                            emin misiniz?'} %></li>
          <% end %>
        </ul>
      </div>
    </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <hr>
    <%= yield(:profile_content) %>
  </div>
</div>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/_top_bar.html.erb
<!-- syntax_highlighting: html -->
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Forum App</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if signed_in? %>
            <li class="has-dropdown">
              <a href="#"><%= "#{current_user.first_name} #{current_user.last_name}" %></a>
              <ul class="dropdown">
                <li><%= link_to 'Profilimi Görüntüle', profile_path(current_user) %></li>
                <li><%= link_to 'Oturumu Kapat', logout_path, method: :delete %></li>
              </ul>
            </li>
        <% else %>
            <li class="divider"></li>
            <li><%= link_to 'Kaydol', register_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Oturum Aç', login_path %></li>
            <li class="divider"></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'foundation-rails' %></title>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/top_bar' %>

    <div class="row">
      <%= render 'layouts/flash_messages' %>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>

  </body>
</html>

app/views/layouts/forums.html.erb
<!-- syntax_highlighting: html -->
<% content_for(:content) do %>
  <div class="large-3 columns panel">
    <h3>KONULAR</h3><hr>
    <ul class="side-nav">
      <%= render @forums %>
    </ul>
  </div>
  
  <div class="large-9 columns">
    <%= yield :forum_content %>
  </div>
<% end %>
 
<%= render template: 'layouts/application' %>